# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.1-node
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

    working_directory: /tmp/build

    steps:
      - checkout

      - run:
          name: "Update Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.13.1-linux-x64/bin/node

      - run:
          name: Check current version of node
          command: node -v

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-yarn-dependencies-

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v2-yarn-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: /tmp
          paths:
             - build

  test-job:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          DB_HOST: localhost
          DB_USERNAME: circleci-demo-go
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: demagog_test

      - image: elasticsearch:7.0.1
        environment:
          - discovery.type=single-node
          - bootstrap.memory_lock=true

    working_directory: /tmp/build

    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: "Update Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.13.1-linux-x64/bin/node

      - run:
          name: Check current version of node
          command: node -v

      # Database setup
      - run: bin/rails db:create
      - run: bin/rails db:schema:load
      - run: bin/rails db:seed

      # Webpack setup
      - run: RAILS_ENV=test bin/webpack

      # run rubocop
      - run:
          name: Run rubocop
          command: bundle exec rubocop

      # run eslint
      - run:
          name: Run eslint
          command: yarn lint

      - run:
          name: Run TypeScript compiler
          command: yarn run tsc --noEmit

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake test

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy-job:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          RAILS_ENV: production
          # This is necessary only to build assets in PRODUCTION mode
          DATABASE_URL: postgres://myuser:mypass@localhost/somedatabase

    working_directory: /tmp/build

    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: "Update Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.13.1-linux-x64/bin/node

      - run:
          name: Check current version of node
          command: node -v

      - add_ssh_keys:
          fingerprints:
            - "58:90:71:2a:18:2d:40:bf:7e:bb:26:a5:3e:4d:d9:25"

      - run: bundler install --with=development

      - run: sudo apt install rsync

      - run:
          name: Deploy to production
          command: |
            bundle exec cap production deploy
            bundle exec cap production unicorn:restart

workflows:
  version: 2
  build-test-hold-deploy:
    jobs:
      - build-job

      - test-job:
          requires:
            - build-job

      - hold:
          type: approval
          requires:
           - test-job
          filters:
            branches:
              only: master

      - deploy-job:
          requires:
            - hold
